"""
Prometheus Metrics Definitions for IAAIR System

Tracks only the essential metrics:
  1. Cache size (gauge)
  2. Hybrid search count & duration (counter + histogram)
  3. AI agent calls count & duration by purpose (counter + histogram)
  4. Tokens generated by AI agent (counter)
  5. Cache hits / misses (counters)
  6. Neo4j template usage (counter)
  7. Number of results retrieved (histogram)
"""

import logging
import threading
from typing import Optional

from prometheus_client import (
    Counter, Histogram, Gauge, CollectorRegistry, generate_latest,
)

logger = logging.getLogger(__name__)


class PrometheusMetrics:
    """Slim Prometheus metrics collector for IAAIR system."""

    def __init__(self, registry: Optional[CollectorRegistry] = None):
        self.registry = registry or CollectorRegistry()
        self._lock = threading.Lock()

        # -- 1. Cache size --
        self.cache_size = Gauge(
            'iaair_cache_size',
            'Current number of entries in each cache',
            ['cache_type'],
            registry=self.registry,
        )

        # -- 2. Hybrid search count & duration --
        self.search_total = Counter(
            'iaair_hybrid_search_total',
            'Total number of hybrid search requests',
            registry=self.registry,
        )

        self.search_duration = Histogram(
            'iaair_hybrid_search_duration_seconds',
            'Hybrid search end-to-end latency in seconds',
            buckets=[0.5, 1.0, 2.0, 5.0, 10.0, 20.0, 30.0, 60.0],
            registry=self.registry,
        )

        # -- 3. AI agent calls --
        self.ai_calls_total = Counter(
            'iaair_ai_calls_total',
            'Total AI agent (LLM) calls',
            ['purpose'],
            registry=self.registry,
        )

        self.ai_call_duration = Histogram(
            'iaair_ai_call_duration_seconds',
            'AI agent call latency in seconds',
            ['purpose'],
            buckets=[0.5, 1.0, 2.0, 5.0, 10.0, 15.0, 30.0],
            registry=self.registry,
        )

        # -- 4. Tokens generated --
        self.tokens_generated_total = Counter(
            'iaair_tokens_generated_total',
            'Total tokens generated by the AI agent',
            ['purpose'],
            registry=self.registry,
        )

        # -- 5. Cache hits / misses --
        self.cache_hits = Counter(
            'iaair_cache_hits_total',
            'Total cache hits',
            ['cache_type'],
            registry=self.registry,
        )

        self.cache_misses = Counter(
            'iaair_cache_misses_total',
            'Total cache misses',
            ['cache_type'],
            registry=self.registry,
        )

        # -- 6. Neo4j template usage --
        self.template_usage = Counter(
            'iaair_template_usage_total',
            'Number of times each Neo4j template was used',
            ['template_key'],
            registry=self.registry,
        )

        # -- 7. Results retrieved --
        self.results_count = Histogram(
            'iaair_results_count',
            'Number of results returned per search',
            buckets=[0, 1, 5, 10, 20, 50, 100],
            registry=self.registry,
        )

    # -- Recording helpers --

    def record_search(self, duration: float):
        """Record a hybrid search request and its duration."""
        with self._lock:
            self.search_total.inc()
            self.search_duration.observe(duration)

    def record_ai_call(self, purpose: str, duration: float, tokens: int = 0):
        """Record an AI agent call."""
        with self._lock:
            self.ai_calls_total.labels(purpose=purpose).inc()
            self.ai_call_duration.labels(purpose=purpose).observe(duration)
            if tokens > 0:
                self.tokens_generated_total.labels(purpose=purpose).inc(tokens)

    def record_cache_hit(self, cache_type: str):
        with self._lock:
            self.cache_hits.labels(cache_type=cache_type).inc()

    def record_cache_miss(self, cache_type: str):
        with self._lock:
            self.cache_misses.labels(cache_type=cache_type).inc()

    def update_cache_size(self, cache_type: str, size: int):
        with self._lock:
            self.cache_size.labels(cache_type=cache_type).set(size)

    def record_template_used(self, template_key: str):
        with self._lock:
            self.template_usage.labels(template_key=template_key).inc()

    def record_results(self, count: int):
        with self._lock:
            self.results_count.observe(count)

    def get_metrics(self) -> str:
        """Return metrics in Prometheus exposition format."""
        return generate_latest(self.registry).decode('utf-8')
